<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-05 18:20
=======
# Generated by Django 5.2.6 on 2025-09-04 20:41
>>>>>>> f6c93994b1d13d2c2165e7d5c6939faa117b49e4

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
<<<<<<< HEAD
                ('id_autor', models.AutoField(db_column='id_autor', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('biografia', models.TextField(blank=True, db_column='biografia', null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
            },
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
>>>>>>> f6c93994b1d13d2c2165e7d5c6939faa117b49e4
        ),
    ]
