# Generated by Django 5.2.6 on 2025-09-06 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='id_autor', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('biografia', models.TextField(blank=True, db_column='biografia', null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(db_column='id_editorial', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('direccion', models.CharField(db_column='direccion', max_length=200)),
                ('telefono', models.CharField(db_column='telefono', max_length=20)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'editorial',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='id_libro', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('resumen', models.TextField(blank=True, db_column='resumen', null=True)),
                ('isbn', models.CharField(db_column='isbn', max_length=20, unique=True)),
                ('anio_publicacion', models.IntegerField(blank=True, db_column='anio_publicacion', null=True)),
                ('autor', models.ForeignKey(db_column='id_autor', on_delete=django.db.models.deletion.CASCADE, to='api_app.autor')),
                ('editorial', models.ForeignKey(db_column='id_editorial', on_delete=django.db.models.deletion.CASCADE, to='api_app.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
            },
        ),
    ]
